// packages/solid/src/client/provider.tsx
import { Suspense, createSignal, Component, onCleanup, onMount } from "solid-js";
import { VoerkaI18nManager } from "@voerkai18n/runtime";

function getInitReady(manager: VoerkaI18nManager) {
    return (
        manager.activeLanguage === manager.defaultLanguage ||
        typeof manager.scope.messages[manager.activeLanguage] !== "function"
    );
}

export type VoerkaI18nSolidProviderProps = {
    fallback?: JSX.Element;
    children: any;
};

export function VoerkaI18nSolidProvider(props: VoerkaI18nSolidProviderProps) {
    const { fallback, children } = props;
    const manager = globalThis.VoerkaI18n;
    const [ready, setReady] = createSignal(getInitReady(manager));
    
    let listener:any

    onMount(() => { 
        listener = manager.on("ready", () => { 
            setReady(true);
        }) 
    });
    onCleanup(() => listener && listener.off()); 

    return <>{
        ready() ? (
            <Suspense fallback={null}> 
                {children}
            </Suspense>
        ) : (
            fallback
        )}
    </>
}

// packages/lynx/src/provider.tsx
import { useEffect, useState } from "@lynx-js/react";
import { useVoerkaI18n } from "./hooks";
import { VoerkaI18nManager } from "@voerkai18n/runtime";

function getInitReady(manager:VoerkaI18nManager){
    return manager.activeLanguage === manager.defaultLanguage
        || typeof(manager.scope.messages[manager.activeLanguage])!=='function'
}   
/**
 *  
 */
export type VoerkaI18nProviderProps= React.PropsWithChildren<{
    fallback?: React.ReactNode;
}>

export function VoerkaI18nProvider(props: VoerkaI18nProviderProps){
    const { fallback, children }  = props
    const { manager } = useVoerkaI18n()
    const [ ready,setReady ] = useState(getInitReady(manager))
    useEffect(()=>{
        const listener = manager.on('ready',()=>{
            setReady(true)
        })
        return ()=> { typeof(listener)==='object' && listener.off() }
    },[])
    return <>
        { ready || (!ready && !fallback) ? children : fallback }
    </>  
}
