// examples/svelte/src/routes/about/+page.svelte
<script lang="ts"> 
import { Translate } from "../../languages"
</script>
<div class="container">
  <h1 class="text-4xl font-bold">
    <Translate message="多语言"/>  
  </h1>  
  <Translate id="about">
    VoerkaI18n是一款功能强大的现代化前端多语言框架，致力于为开发者提供灵活、高效且全链路的国际化支持。其核心优势在于深度适配主流技术生态，无缝支持Vue、React、SolidJS、Svelte等前端框架，并兼容Node.js服务端及原生JavaScript项目，真正实现跨平台多场景覆盖。
该方案创新性地提出了“全自动化翻译工作流”，通过智能CLI工具自动扫描源码提取待翻译文本，结合可视化编辑器实现翻译协作，大幅降低人工维护成本。其运行时动态加载能力支持语言包按需加载，显著优化性能。功能上，除基础的变量插值、复数规则、日期货币格式化外，还提供强大的上下文敏感翻译、微翻译模式（精准更新局部内容）及智能诊断工具，可自动检测翻译覆盖率与语法错误。
VoerkaI18n的突破性设计体现在“去中心化”管理架构，开发者可将翻译文件与代码库解耦，通过轻量级API实现云端协同。其类型安全的TypeScript支持和响应式语言切换机制，进一步提升了开发体验。无论是轻量应用还是大型工程，VoerkaI18n均以高扩展性和极简API重新定义了国际化开发范式，成为全球化项目的理想之选。
    </Translate>
    <h1>MIT许可证</h1>
    <Translate id="license" className="sdds" style={{border:'1px solid red'}} >
版权所有 (c) [年份] [版权持有者]
特此免费授予任何获得本软件及相关文档文件（以下简称“软件”）副本的人，不受限制地处理本软件的权限，包括但不限于使用、复制、修改、合并、发布、分发、再许可和/或出售本软件的副本，并允许获得本软件的人这样做，但须满足以下条件：
上述版权声明和本许可声明应包含在本软件的所有副本或重要部分中。
本软件“按原样”提供，不提供任何形式的明示或暗示的担保，包括但不限于对适销性、特定用途适用性和非侵权性的担保。在任何情况下，作者或版权持有者均不对任何索赔、损害或其他责任负责，无论是在合同、侵权或其他行为中产生的，还是与本软件或本软件的使用或其他交易有关的。
</Translate>
</div>

// examples/nextjs/src/app/about/page.tsx
 
import { Translate } from "@/languages/client";

export default function About() {
  return (
    <> 
    <div className="flex flex-col items-center justify-center gap-4 p-8 mt-18 ">       
    <Translate id="about">
        VoerkaI18n是一款功能强大的现代化前端多语言框架，致力于为开发者提供灵活、高效且全链路的国际化支持。其核心优势在于深度适配主流技术生态，无缝支持Vue、React、SolidJS、Svelte等前端框架，并兼容Node.js服务端及原生JavaScript项目，真正实现跨平台多场景覆盖。
该方案创新性地提出了“全自动化翻译工作流”，通过智能CLI工具自动扫描源码提取待翻译文本，结合可视化编辑器实现翻译协作，大幅降低人工维护成本。其运行时动态加载能力支持语言包按需加载，显著优化性能。功能上，除基础的变量插值、复数规则、日期货币格式化外，还提供强大的上下文敏感翻译、微翻译模式（精准更新局部内容）及智能诊断工具，可自动检测翻译覆盖率与语法错误。
VoerkaI18n的突破性设计体现在“去中心化”管理架构，开发者可将翻译文件与代码库解耦，通过轻量级API实现云端协同。其类型安全的TypeScript支持和响应式语言切换机制，进一步提升了开发体验。无论是轻量应用还是大型工程，VoerkaI18n均以高扩展性和极简API重新定义了国际化开发范式，成为全球化项目的理想之选。
        </Translate>
        <h1>MIT许可证</h1>
        <Translate id="license" className="sdds" style={{border:'1px solid red'}} >
版权所有 (c) [年份] [版权持有者]
特此免费授予任何获得本软件及相关文档文件（以下简称“软件”）副本的人，不受限制地处理本软件的权限，包括但不限于使用、复制、修改、合并、发布、分发、再许可和/或出售本软件的副本，并允许获得本软件的人这样做，但须满足以下条件：
上述版权声明和本许可声明应包含在本软件的所有副本或重要部分中。
本软件“按原样”提供，不提供任何形式的明示或暗示的担保，包括但不限于对适销性、特定用途适用性和非侵权性的担保。在任何情况下，作者或版权持有者均不对任何索赔、损害或其他责任负责，无论是在合同、侵权或其他行为中产生的，还是与本软件或本软件的使用或其他交易有关的。
</Translate>
    </div>
    </>
  );
}
