// examples/vue2/src/components/LanguageBar.vue
<template>
    <ul class="language-bar"> 
        <li v-for="lang in languages">
            <button 
                class="lang-button"
                @click="changeLanguage(lang.name)" 
                :class="{ active: lang.name === activeLanguage }"
                :key="lang.name">{{ lang.title }}-{{ lang.name }}</button>
        </li> 
    </ul>
  </template>
  
  <script lang="ts">
  import { i18nScope } from '../languages';
  import { withI18n } from '@voerkai18n/vue2';

  export default withI18n({   
  },i18nScope)

  </script>
  
  <!-- Add "scoped" attribute to limit CSS to this component only -->
  <style scoped lang="less">
  .language-bar{
    padding: 4px;
    margin-right: 6px;
    display: flex;
    flex-direction: row;
    align-items: center;
    justify-content: center;
    
    & > li{
        display: inline-block;
        margin-right: 2px;
        list-style: none;
    }
  }
  .lang-button{
    cursor: pointer;
    padding: 6px;
    margin-right: 6px;
    border: 1px solid #42b983;
    border-radius: 4px;
    background-color: white;
    &.active{
      background-color: #42b983;
      color: white;
    }
  }
  </style>

// examples/react/src/components/LanguageBar.tsx
 
 

import React from 'react'; 
import { useVoerkaI18n } from '@voerkai18n/react';
import classNames from 'classnames'

const LanguageBar: React.FC = () => {
  const { activeLanguage, changeLanguage, languages } = useVoerkaI18n();
  return (
    <div className="flex md:order-2 flex-row justify-items-center align-middle">
      {languages.map((lang) => (
        <button 
          key={lang.name} 
          onClick={() => changeLanguage(lang.name)} 
          className={classNames(
            "cursor-pointer border border-gray-300 focus:outline-none focus:ring-4 focus:ring-gray-100 font-medium rounded-lg text-sm px-5 py-2.5 me-2 dark:bg-gray-800 dark:text-white dark:border-gray-600 dark:hover:bg-gray-700 dark:hover:border-gray-600 dark:focus:ring-gray-700",
            lang.name === activeLanguage  ? "bg-blue-700 text-white border-gray-300" :"text-gray-900"
          )}
        >{lang.name}</button>
      ))}
    </div>
  );
};

export default LanguageBar;
