// examples/vue3/src/components/Loading.vue
<template>
    <div class="loading">
         loading...
    </div>
</template>
 
<style scoped>
  .loading {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    display: flex;
    justify-content: center;
    align-items: center;
    background-color: rgba(255, 255, 255, 0.8); /* 半透明背景 */
    z-index: 9999; /* 确保覆盖父容器 */
  }
  </style>

// examples/react/src/components/Loading.tsx
 
 

import React from 'react'; 
const Loading: React.FC = () => {
  return (
    <div className="loading" style={{
        'position': 'absolute',
        'top': 0,
        'left': 0,
        'width': '100%',
        'height': '100%',
        'display': 'flex',
        'justifyContent': 'center',
        'alignItems': 'center',
        'backgroundColor': 'rgba(255, 255, 255, 0.8)', 
        'zIndex': 9999
    }}>
      加载中...
    </div>
  );
};

export default Loading;
