// packages/react/src/context.tsx
import { VoerkaI18nLanguageDefine, VoerkaI18nScope, VoerkaI18nTranslate } from "@voerkai18n/runtime"
import React, { useCallback, useEffect, useState } from "react"


export type VoerkaI18nContextProps = {
    changeLanguage : (newLanguage:string)=>Promise<void> 
    defaultLanguage: string   
    activeLanguage : string   
    languages      : VoerkaI18nLanguageDefine[]
    t              : VoerkaI18nTranslate
    changing       : boolean
}

export const VoerkaI18nContext = React.createContext<VoerkaI18nContextProps>({
    languages:[],
    activeLanguage:'zh-CN',
    defaultLanguage:'zh-CN',
    changeLanguage:async () =>{},
    t:()=>'',
    changing: false
})

VoerkaI18nContext.displayName = 'VoerkaI18nProvider'

export type VoerkaI18nProviderProps = React.PropsWithChildren<{ 
    scope     : VoerkaI18nScope
    fallback? : React.ReactNode
}>

export function VoerkaI18nProvider(props:VoerkaI18nProviderProps){
    const { scope,fallback }       = props
    const [language, setLanguage ] = useState(VoerkaI18n.activeLanguage); 
    const [ready, setReady ]       = useState(false);
    const [changing, setChanging]  = useState(false)
    
    useEffect(() => { 
        const onChangeLanguage = (newLanguage:string) => setLanguage(newLanguage) 
        VoerkaI18n.ready(()=>{            
            setReady(true)
        })
        const listener = VoerkaI18n.on("change",onChangeLanguage) as any
        return () => listener.off()
    },[]);

    
    const changeLanguage = useCallback((newLanguage:string) => {
        setChanging(true)
        return VoerkaI18n.change(newLanguage).then((lng) => {
            setLanguage(lng) 
            setChanging(false)
        })
    },[ language ])

    const value ={
        changeLanguage,
        activeLanguage : language,    
        defaultLanguage: VoerkaI18n.scope.defaultLanguage,
        languages      : VoerkaI18n.languages,        
        changing       : changing,
        t              : scope.t
    }

    return ( <><VoerkaI18nContext.Provider value={value}>
            { (!ready && fallback) ? props.fallback : props.children }
        </VoerkaI18nContext.Provider> </>)
}

// packages/svelte/src/lib/context.svelte
<script lang="ts">

import { onDestroy, onMount, setContext } from 'svelte';
import type { VoerkaI18nEventSubscriber } from '@voerkai18n/runtime';

const { scope = VoerkaI18n.scope,children } = $props() 
let activeLanguage = $state(VoerkaI18n.activeLanguage);
let ready = $state(false);

let subscriber:VoerkaI18nEventSubscriber | undefined;

scope.on("ready",()=>{
    ready = true
})


onMount(()=>{    

    subscriber = scope.on('change', (newLanguage:string) => {
        activeLanguage = newLanguage
    })
});

onDestroy(()=>{
    subscriber && subscriber.off()
});
 


setContext('Voerkai18nContext', {
    activeLanguage,
    defaultLanguage: VoerkaI18n.defaultLanguage,
    changeLanguage : scope.change.bind(scope),
    languages      : VoerkaI18n.languages,  
    t              : scope.t,   
    manager        : VoerkaI18n,
    scope,
   
});

</script>

{#if ready}
    {@render children?.()}
{/if}
